### PR TITLE
feat: add api key

### PR DESCRIPTION
**Pull request by leoguillaume**
# Why ?
In production, if you want to publish API on internet, you needs to protect the API by a key.

# What ? 
Add the possibility to set up an API key in the config file, using the API_KEY environment variable (optional).
The API_KEY scheme is a classic bearer token. This authentication appears on the Swagger interface if an API_KEY is set:
 
The API_KEY scheme is a classic bearer.  This authentication appears on the swagger here if a API_KEY is set : 
image

image

If the API_KEY is not set up, the authentication is not displayed.

### CODE REVIEW

**Comment by Ledoux** [comment]
Is there a reason that this feature could not be integrated ? This would be helpful

**Comment by fedirz** [comment]
My reasoning for not merging this in was that I thought implementing auth is out of scope of this project. I don't want to add extra features that I'll have to be responsible for maintaining in the future. Plus if you do want auth you'd rarely use basic auth you'd likely want something else such as token or session based auth.

However, given that the code has already been written and that it seems like multiple people I want it to be a part of the project, I'll add it in. I will need to edit the PR to make the changes work with the new project structure.

**Comment by PierreMesure** [comment]
I see that you're working at Etalab Léo. Cool to see that you're looking at deploying Whisper models as a service. 😊
Do you also have embeddings and LLM behind OpenAI-compatible APIs?

That's what we're trying to do at the Swedish Ministry of Finance. We currently use Ollama for embeddings, models and Litserve for more advanced assistants (such as RAG-systems built with LlamaIndex).

We are not there yet but when we need to scale up the management of credentials, I think we will put things behind LiteLLM.

**Comment by fedirz** [comment]
Done in #141. @leoguillaume thx for the contribution

**Pull request closed without merging**
