### PR TITLE
avoid small pieces data received by web socket

### PR DESCRIPTION
**Pull request by afpro**

### CODE REVIEW

**Comment by fedirz** [comment]
Thanks for creating the pr. Could you please provide some context on what issue(s) this change addresses?

**Comment by afpro** [comment]
> Thanks for creating the pr. Could you please provide some context on what issue(s) this change addresses?

small pieces data + concurrent access ws (about 8-10 connection), cause ws timeout exception.

**Comment by fedirz** [comment]
I'll test this out within the next couple of days and merge this in. Thanks!

**Comment by afpro** [comment]
i am not working on asr project for a while, will delete this pr and forked project.

**Pull request closed without merging**
